kumuluzee:
  name: notification-service
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count"
  openapi:
    enabled: true
    ui:
      enabled: true
  logs:
    loggers:
      - name: ''
        level: INFO
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/mainDB
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  security:
    keycloak:
      json: '{
               "realm": "rso",
               "bearer-only": true,
               "auth-server-url": "https://keycloak.mjamsek.com/auth",
               "ssl-required": "external",
               "resource": "notification-service",
               "confidential-port": 0
             }'
  rest-client:
    registrations:
      - class: twilio-api
        url: https://api.twilio.com/2010-04-01
notifications:
  mail:
    host: smtp.yandex.com
    port: 465
    display-name: E-store
    username: not_set
    password: not_set
  sms:
    api-sid: not_set
    api-key: not_set
    number: not_set
