kumuluzee:
  name: notification-service
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count"
  openapi:
    enabled: true
    ui:
      enabled: true
  config:
    consul:
      agent: http://localhost:8500
      start-retry-delay-ms: 500
      max-retry-delay-ms: 900000
  logs:
    loggers:
      - name: ''
        level: INFO
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  streaming:
    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: group1
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  security:
    keycloak:
      json: '{
               "realm": "rso",
               "bearer-only": true,
               "auth-server-url": "https://keycloak.mjamsek.com/auth",
               "ssl-required": "external",
               "resource": "notification-service",
               "confidential-port": 0
             }'
  rest-client:
    registrations:
      - class: twilio-api
        url: https://api.twilio.com/2010-04-01
notifications:
  mail:
    host: smtp.yandex.com
    port: 465
    display-name: E-store
    username: not_set
    password: not_set
    tmp-dir: temp
  sms:
    api-sid: not_set
    api-key: not_set
    number: not_set
service-config:
  maintenance: false

