apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: notifications-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: notifications-app-deployment
    spec:
      containers:
        - name: notifications-app-container
          image: rso6315/notification-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_STREAMING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS
              value: kafka-service.e-store:9092
            - name: NOTIFICATIONS_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notifications-pass
                  key: NOTIFICATIONS_MAIL_USERNAME
            - name: NOTIFICATIONS_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notifications-pass
                  key: NOTIFICATIONS_MAIL_PASSWORD
            - name: NOTIFICATIONS_SMS_API-SID
              valueFrom:
                secretKeyRef:
                  name: notifications-pass
                  key: NOTIFICATIONS_SMS_API-SID
            - name: NOTIFICATIONS_SMS_API-KEY
              valueFrom:
                secretKeyRef:
                  name: notifications-pass
                  key: NOTIFICATIONS_SMS_API-KEY
            - name: NOTIFICATIONS_SMS_NUMBER
              valueFrom:
                secretKeyRef:
                  name: notifications-pass
                  key: NOTIFICATIONS_SMS_NUMBER
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31011
      targetPort: 8080
      protocol: TCP
  selector:
    app: notifications-app-deployment