FROM openjdk:11-jre-slim

ENV JAVA_ENV=PRODUCTION
ENV KUMULUZEE_ENV_NAME=prod
ENV KUMULUZEE_ENV_PROD=true
ENV KUMULUZEE_LOGS_LOGGERS0_LEVEL=INFO

ENV KUMULUZEE_REST-CLIENT_REGISTRATIONS0_URL=https://api.twilio.com/2010-04-01
ENV NOTIFICATIONS_MAIL_HOST=smtp.yandex.com
ENV NOTIFICATIONS_MAIL_PORT=465
ENV NOTIFICATIONS_MAIL_DISPLAY-NAME=E-store
ENV NOTIFICATIONS_MAIL_USERNAME=not_set
ENV NOTIFICATIONS_MAIL_PASSWORD=not_set
ENV NOTIFICATIONS_MAIL_TMP-DIR=/app/tmp
ENV NOTIFICATIONS_SMS_API-SID=not_set
ENV NOTIFICATIONS_SMS_API-KEY=not_set
ENV NOTIFICATIONS_SMS_NUMBER=not_set

RUN mkdir /app
RUN mkdir /app/tmp

WORKDIR /app

ADD ./api/v1/target/notification-service.jar /app

EXPOSE 8080

CMD ["java", "-jar", "notification-service.jar"]
